// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: migration.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from migration.proto</summary>
public static partial class MigrationReflection
{

    #region Descriptor
    /// <summary>File descriptor for migration.proto</summary>
    public static pbr::FileDescriptor Descriptor
    {
        get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MigrationReflection()
    {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            string.Concat(
              "Cg9taWdyYXRpb24ucHJvdG8ihgEKEE1pZ3JhdGlvblBheWxvYWQSJgoOb3Rw",
              "X3BhcmFtZXRlcnMYASADKAsyDi5PVFBQYXJhbWV0ZXJzEg8KB3ZlcnNpb24Y",
              "AiABKAUSEgoKYmF0Y2hfc2l6ZRgDIAEoBRITCgtiYXRjaF9pbmRleBgEIAEo",
              "BRIQCghiYXRjaF9pZBgFIAEoBSJuCg1PVFBQYXJhbWV0ZXJzEg4KBnNlY3Jl",
              "dBgBIAEoDBIMCgRuYW1lGAIgASgJEg4KBmlzc3VlchgDIAEoCRIRCglhbGdv",
              "cml0aG0YBCABKAUSDgoGZGlnaXRzGAUgASgFEgwKBHR5cGUYBiABKAViBnBy",
              "b3RvMw=="));
        descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
            new pbr::FileDescriptor[] { },
            new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MigrationPayload), global::MigrationPayload.Parser, new[]{ "OtpParameters", "Version", "BatchSize", "BatchIndex", "BatchId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::OTPParameters), global::OTPParameters.Parser, new[]{ "Secret", "Name", "Issuer", "Algorithm", "Digits", "Type" }, null, null, null, null)
            }));
    }
    #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class MigrationPayload : pb::IMessage<MigrationPayload>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
    private static readonly pb::MessageParser<MigrationPayload> _parser = new pb::MessageParser<MigrationPayload>(() => new MigrationPayload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MigrationPayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::MigrationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MigrationPayload()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MigrationPayload(MigrationPayload other) : this()
    {
        otpParameters_ = other.otpParameters_.Clone();
        version_ = other.version_;
        batchSize_ = other.batchSize_;
        batchIndex_ = other.batchIndex_;
        batchId_ = other.batchId_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MigrationPayload Clone()
    {
        return new MigrationPayload(this);
    }

    /// <summary>Field number for the "otp_parameters" field.</summary>
    public const int OtpParametersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::OTPParameters> _repeated_otpParameters_codec
        = pb::FieldCodec.ForMessage(10, global::OTPParameters.Parser);
    private readonly pbc::RepeatedField<global::OTPParameters> otpParameters_ = new pbc::RepeatedField<global::OTPParameters>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OTPParameters> OtpParameters
    {
        get { return otpParameters_; }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 2;
    private int version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Version
    {
        get { return version_; }
        set
        {
            version_ = value;
        }
    }

    /// <summary>Field number for the "batch_size" field.</summary>
    public const int BatchSizeFieldNumber = 3;
    private int batchSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BatchSize
    {
        get { return batchSize_; }
        set
        {
            batchSize_ = value;
        }
    }

    /// <summary>Field number for the "batch_index" field.</summary>
    public const int BatchIndexFieldNumber = 4;
    private int batchIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BatchIndex
    {
        get { return batchIndex_; }
        set
        {
            batchIndex_ = value;
        }
    }

    /// <summary>Field number for the "batch_id" field.</summary>
    public const int BatchIdFieldNumber = 5;
    private int batchId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BatchId
    {
        get { return batchId_; }
        set
        {
            batchId_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other)
    {
        return Equals(other as MigrationPayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MigrationPayload other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (!otpParameters_.Equals(other.otpParameters_)) return false;
        if (Version != other.Version) return false;
        if (BatchSize != other.BatchSize) return false;
        if (BatchIndex != other.BatchIndex) return false;
        if (BatchId != other.BatchId) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode()
    {
        int hash = 1;
        hash ^= otpParameters_.GetHashCode();
        if (Version != 0) hash ^= Version.GetHashCode();
        if (BatchSize != 0) hash ^= BatchSize.GetHashCode();
        if (BatchIndex != 0) hash ^= BatchIndex.GetHashCode();
        if (BatchId != 0) hash ^= BatchId.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
#else
    otpParameters_.WriteTo(output, _repeated_otpParameters_codec);
    if (Version != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Version);
    }
    if (BatchSize != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(BatchSize);
    }
    if (BatchIndex != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(BatchIndex);
    }
    if (BatchId != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(BatchId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
        otpParameters_.WriteTo(ref output, _repeated_otpParameters_codec);
        if (Version != 0)
        {
            output.WriteRawTag(16);
            output.WriteInt32(Version);
        }
        if (BatchSize != 0)
        {
            output.WriteRawTag(24);
            output.WriteInt32(BatchSize);
        }
        if (BatchIndex != 0)
        {
            output.WriteRawTag(32);
            output.WriteInt32(BatchIndex);
        }
        if (BatchId != 0)
        {
            output.WriteRawTag(40);
            output.WriteInt32(BatchId);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(ref output);
        }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize()
    {
        int size = 0;
        size += otpParameters_.CalculateSize(_repeated_otpParameters_codec);
        if (Version != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Version);
        }
        if (BatchSize != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(BatchSize);
        }
        if (BatchIndex != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(BatchIndex);
        }
        if (BatchId != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(BatchId);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MigrationPayload other)
    {
        if (other == null)
        {
            return;
        }
        otpParameters_.Add(other.otpParameters_);
        if (other.Version != 0)
        {
            Version = other.Version;
        }
        if (other.BatchSize != 0)
        {
            BatchSize = other.BatchSize;
        }
        if (other.BatchIndex != 0)
        {
            BatchIndex = other.BatchIndex;
        }
        if (other.BatchId != 0)
        {
            BatchId = other.BatchId;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
#else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          otpParameters_.AddEntriesFrom(input, _repeated_otpParameters_codec);
          break;
        }
        case 16: {
          Version = input.ReadInt32();
          break;
        }
        case 24: {
          BatchSize = input.ReadInt32();
          break;
        }
        case 32: {
          BatchIndex = input.ReadInt32();
          break;
        }
        case 40: {
          BatchId = input.ReadInt32();
          break;
        }
      }
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if ((tag & 7) == 4)
            {
                // Abort on any end group tag.
                return;
            }
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                case 10:
                    {
                        otpParameters_.AddEntriesFrom(ref input, _repeated_otpParameters_codec);
                        break;
                    }
                case 16:
                    {
                        Version = input.ReadInt32();
                        break;
                    }
                case 24:
                    {
                        BatchSize = input.ReadInt32();
                        break;
                    }
                case 32:
                    {
                        BatchIndex = input.ReadInt32();
                        break;
                    }
                case 40:
                    {
                        BatchId = input.ReadInt32();
                        break;
                    }
            }
        }
    }
#endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class OTPParameters : pb::IMessage<OTPParameters>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
    private static readonly pb::MessageParser<OTPParameters> _parser = new pb::MessageParser<OTPParameters>(() => new OTPParameters());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OTPParameters> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor
    {
        get { return global::MigrationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor
    {
        get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OTPParameters()
    {
        OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OTPParameters(OTPParameters other) : this()
    {
        secret_ = other.secret_;
        name_ = other.name_;
        issuer_ = other.issuer_;
        algorithm_ = other.algorithm_;
        digits_ = other.digits_;
        type_ = other.type_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OTPParameters Clone()
    {
        return new OTPParameters(this);
    }

    /// <summary>Field number for the "secret" field.</summary>
    public const int SecretFieldNumber = 1;
    private pb::ByteString secret_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Secret
    {
        get { return secret_; }
        set
        {
            secret_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name
    {
        get { return name_; }
        set
        {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
    }

    /// <summary>Field number for the "issuer" field.</summary>
    public const int IssuerFieldNumber = 3;
    private string issuer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Issuer
    {
        get { return issuer_; }
        set
        {
            issuer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
    }

    /// <summary>Field number for the "algorithm" field.</summary>
    public const int AlgorithmFieldNumber = 4;
    private int algorithm_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Algorithm
    {
        get { return algorithm_; }
        set
        {
            algorithm_ = value;
        }
    }

    /// <summary>Field number for the "digits" field.</summary>
    public const int DigitsFieldNumber = 5;
    private int digits_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Digits
    {
        get { return digits_; }
        set
        {
            digits_ = value;
        }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 6;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Type
    {
        get { return type_; }
        set
        {
            type_ = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other)
    {
        return Equals(other as OTPParameters);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OTPParameters other)
    {
        if (ReferenceEquals(other, null))
        {
            return false;
        }
        if (ReferenceEquals(other, this))
        {
            return true;
        }
        if (Secret != other.Secret) return false;
        if (Name != other.Name) return false;
        if (Issuer != other.Issuer) return false;
        if (Algorithm != other.Algorithm) return false;
        if (Digits != other.Digits) return false;
        if (Type != other.Type) return false;
        return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode()
    {
        int hash = 1;
        if (Secret.Length != 0) hash ^= Secret.GetHashCode();
        if (Name.Length != 0) hash ^= Name.GetHashCode();
        if (Issuer.Length != 0) hash ^= Issuer.GetHashCode();
        if (Algorithm != 0) hash ^= Algorithm.GetHashCode();
        if (Digits != 0) hash ^= Digits.GetHashCode();
        if (Type != 0) hash ^= Type.GetHashCode();
        if (_unknownFields != null)
        {
            hash ^= _unknownFields.GetHashCode();
        }
        return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString()
    {
        return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
#else
    if (Secret.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Secret);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (Issuer.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Issuer);
    }
    if (Algorithm != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Algorithm);
    }
    if (Digits != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Digits);
    }
    if (Type != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
    {
        if (Secret.Length != 0)
        {
            output.WriteRawTag(10);
            output.WriteBytes(Secret);
        }
        if (Name.Length != 0)
        {
            output.WriteRawTag(18);
            output.WriteString(Name);
        }
        if (Issuer.Length != 0)
        {
            output.WriteRawTag(26);
            output.WriteString(Issuer);
        }
        if (Algorithm != 0)
        {
            output.WriteRawTag(32);
            output.WriteInt32(Algorithm);
        }
        if (Digits != 0)
        {
            output.WriteRawTag(40);
            output.WriteInt32(Digits);
        }
        if (Type != 0)
        {
            output.WriteRawTag(48);
            output.WriteInt32(Type);
        }
        if (_unknownFields != null)
        {
            _unknownFields.WriteTo(ref output);
        }
    }
#endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize()
    {
        int size = 0;
        if (Secret.Length != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Secret);
        }
        if (Name.Length != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
        }
        if (Issuer.Length != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Issuer);
        }
        if (Algorithm != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Algorithm);
        }
        if (Digits != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Digits);
        }
        if (Type != 0)
        {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
        }
        if (_unknownFields != null)
        {
            size += _unknownFields.CalculateSize();
        }
        return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OTPParameters other)
    {
        if (other == null)
        {
            return;
        }
        if (other.Secret.Length != 0)
        {
            Secret = other.Secret;
        }
        if (other.Name.Length != 0)
        {
            Name = other.Name;
        }
        if (other.Issuer.Length != 0)
        {
            Issuer = other.Issuer;
        }
        if (other.Algorithm != 0)
        {
            Algorithm = other.Algorithm;
        }
        if (other.Digits != 0)
        {
            Digits = other.Digits;
        }
        if (other.Type != 0)
        {
            Type = other.Type;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input)
    {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
#else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Secret = input.ReadBytes();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 26: {
          Issuer = input.ReadString();
          break;
        }
        case 32: {
          Algorithm = input.ReadInt32();
          break;
        }
        case 40: {
          Digits = input.ReadInt32();
          break;
        }
        case 48: {
          Type = input.ReadInt32();
          break;
        }
      }
    }
#endif
    }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
    {
        uint tag;
        while ((tag = input.ReadTag()) != 0)
        {
            if ((tag & 7) == 4)
            {
                // Abort on any end group tag.
                return;
            }
            switch (tag)
            {
                default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                case 10:
                    {
                        Secret = input.ReadBytes();
                        break;
                    }
                case 18:
                    {
                        Name = input.ReadString();
                        break;
                    }
                case 26:
                    {
                        Issuer = input.ReadString();
                        break;
                    }
                case 32:
                    {
                        Algorithm = input.ReadInt32();
                        break;
                    }
                case 40:
                    {
                        Digits = input.ReadInt32();
                        break;
                    }
                case 48:
                    {
                        Type = input.ReadInt32();
                        break;
                    }
            }
        }
    }
#endif

}

#endregion


#endregion Designer generated code
